name: Deploy static site to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sunit-landing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: sunit-landing/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Determine base path for Pages
        shell: bash
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          if [[ "$REPO_NAME" == *.github.io ]]; then
            echo "NEXT_BASE_PATH=" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_BASE_PATH=" >> $GITHUB_ENV
          else
            echo "NEXT_BASE_PATH=/$REPO_NAME" >> $GITHUB_ENV
            echo "NEXT_PUBLIC_BASE_PATH=/$REPO_NAME" >> $GITHUB_ENV
          fi

      - name: Build static site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: sunit-landing/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
